AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  python37:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: fmi-python37
      ContentUri: .
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: makefile
