AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  python39:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: fmi-python39
      ContentUri: .
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: makefile
