AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  python38:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: fmi-python38
      ContentUri: .
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: makefile
